name: Publish Package to npmjs.com
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          registry-url: https://registry.npmjs.org/
          scope: "@irsyadadl"
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build
      - name: Publish to npm
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
